#!/bin/false

KERNEL_VERSION=6
KERNEL_PATCHLEVEL=15
KERNEL_SUBLEVEL=5
KERNEL_VERSION_NAME="${KERNEL_VERSION}.${KERNEL_PATCHLEVEL}.${KERNEL_SUBLEVEL}"

ALPINE_VERSION="3.22"
ALPINE_ARCH="armv7"

#CONFIG_KERNEL="y"
